### ISSUE TITLE
installation: fix compatibility with Celery 4.0

### ISSUE THREAD

**Issue by jirikuncar** [inveniosoftware/flask-celeryext#22]
### Proposal

Pin `celery<4.0` for 0.2.2 and bump in 0.3.x or 1.x.

See http://docs.celeryproject.org/en/latest/whatsnew-4.0.html#v400-upgrade-settings

--
addresses https://github.com/inveniosoftware/invenio-celery/issues/37

**Comment by lnielsen** [comment]
Here some thoughts on possible ways to attack it:

### 4.0 vs 3.1+4.0 support
I think it might be possible to keep supporting both 3.1 and 4.0 with the same code base without too much hassle. The main issue in supporting both is properly the settings that have been renamed and the upper vs lowercase names.

### Lowercase or uppercase settings names (independent of v4.0 vs 3.1+4.0)
It seems from the release notes that it's a valid use case to keep using uppercase names with a prefix (see "For Django users and others who want to keep uppercase names"). As long as we load the celery configuration from the Flask app I think it makes sense to keep using uppercase variable names with ``CELERY_`` prefix, since this is the pattern used by FLASK. Alternatively if we go with 4.0 only, then we could consider loading the celery configuration from a separate file.

### 4.0 only support
If we go with 4.0 only support, I would first make a new release 0.2.3 which requires Celery v3.1.25 - to ensure compatibility between 3.1 and 4.0 messages, and then afterwards make a 1.0 release for Celery 4.

**Comment by fuhrysteve** [comment]
It's probably best to do a major release and drop support for the 3.x line. This library is too small and young to be burdened by the past.

For 3.0 support, folks can always just pin `flaskceleryext>=0.2,<0.3`

**Comment by lnielsen** [comment]
@fuhrysteve Thanks for tipping in. Do you have an opinion about with respect to lower/upper case setting names?

**Comment by fuhrysteve** [comment]
Since Flask users should already have a config file, I don't really see any advantage to maintaining a separate config file for Celery. I don't have a separate config file for SQLAlchemy, for example. If someone really wanted that, it should be easy enough to customize `create_celery_app`

It seems to me that Flask users fall squarely in the category of _For Django users and others who want to keep uppercase names_ http://celery.readthedocs.io/en/latest/whatsnew-4.0.html#lowercase-setting-names

Not to backpedal too much, but if that's the way to go, it might be trivial to achieve backwards and forwards compatibility. I just wouldn't make a fuss over maintaining backwards compatibility with celery 3.x if it makes things messy.

**Comment by hachreak** [comment]
Any news about this Issue? :smile: 
I tried to install now `invenio-webhooks` from git and it raises a conflict exception about celery 3 vs 4.

**Comment by lnielsen** [comment]
There's already a release out of flask-celeryext which pins celery <4, is that not enough? I don't think I have time to work on it until next week.

**Comment by hachreak** [comment]
As you can see [here](https://travis-ci.org/hachreak/invenio-webhooks/jobs/176435006) (test branch is a copy of master), In webhooks:
 - in `extra_require` is requiring `celery>=3.0` and it's installing `celery 4`
 - in `tests_require` is requiring `Flask-CeleryExt>=0.1.0` that require `celery<4`.

**Comment by lnielsen** [comment]
I think the most future proof is to:

- in ``extra_require`` replace ``celery>=3.0`` with ``Flask-CeleryExt>=0.2.3`` (note v0.2.3 which is the one that pins Celery).
- in ``tests_require`` remove ``Flask-CeleryExt>=0.2.2``

This way we only have to fix Flask-CeleryExt in the future if Celery is new major version releases, and when Flask-CeleryExt is updated to support v4 you don't need to unpin Invenio-Webhooks again.

**Comment by jirikuncar** [comment]
> ... `Flask-CeleryExt>=0.2.3` (note v0.2.3 ...

IMHO it should be 0.2.2 see https://pypi.python.org/pypi/Flask-CeleryExt

**Comment by lnielsen** [comment]
@jirikuncar Correct :-)

**Comment by lnielsen** [comment]
Fixed in #28
