### ISSUE TITLE
How to get a flask.g variable  inside a task set in a before_request decorater func or a view func?

### ISSUE THREAD

**Issue by bydeath** [inveniosoftware/flask-celeryext#33]
How to get a flask.g variable  inside a task set in a before_request decorater func or a view func?

**Comment by slint** [comment]
I suspect that this shouldn't be possible since a Celery task shouldn't expect or be aware of any kind of flask request globals (like `flask.g`, `flask.request`, etc). When you are running a task inside a request you should pass anything that is specific to the current request to the task via arguments

**Comment by bydeath** [comment]
@slint Thanks for your replay. This is a good way to pass flask request globals to a celery task: [https://gist.github.com/aviaryan/8620390d832678f0de4528bbc4b4b272](https://gist.github.com/aviaryan/8620390d832678f0de4528bbc4b4b272)
